name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Executar lint
        run: npm run lint

      - name: Executar testes
        run: npm run test:dev -- --ci --coverage

      - name: Build da aplicação
        run: npm run build

      - name: Arquivos gerados no build
        run: ls -la dist/